use_frameworks!

target 'ZHRefresh_Example' do
  pod 'ZHRefresh', :path => '../'
  pod 'SnapKit', '~> 4.0.0'

  target 'ZHRefresh_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
